/*
## Summary
Prepares a core list of unique topic codes (eg, ANZSRC FoR codes).

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0

## Requires
table raw_forcodes

## Creates
table core_fors

*/
const compile = ({
  project = "",
  dataset = "",
  replace = false,
  version = "",
}) => `
-- generated by: ${require("path").basename(__filename)}
BEGIN 
  -- ${replace ? "CREATE OR REPLACE TABLE" : "CREATE TABLE IF NOT EXISTS"} \`${project}.${dataset}.core_fors${version}\` AS (
  --   SELECT '2008' as vers, LENGTH(code) AS len, code, name FROM \`${project}.${dataset}.raw_forcodes_2008_${version}\` WHERE LENGTH(code) <= 4 UNION ALL
  --   SELECT '2020' as vers, LENGTH(code) AS len, code, name FROM \`${project}.${dataset}.raw_forcodes_2020_${version}\` WHERE LENGTH(code) <= 4 UNION ALL
  --   ORDER BY vers,len,code,name
  -- );
  ${replace ? "CREATE OR REPLACE TABLE" : "CREATE TABLE IF NOT EXISTS"} \`${project}.${dataset}.core_fors${version}\` AS (
    SELECT 
      vers, 
      LENGTH(code) AS len, 
      code, 
      name 
    FROM \`${project}.${dataset}.raw_forcodes${version}\` 
    WHERE LENGTH(code) <= 4 AND vers = '2020'
    ORDER BY vers,len,code,name
  );
  ALTER TABLE \`${project}.${dataset}.core_fors${version}\` SET OPTIONS(description='Field of Research codes, defined by ANZSRC');
  ALTER TABLE ${project}.${dataset}.core_fors${version}
  ALTER COLUMN vers SET OPTIONS (description="The version of ANZSRC subject classification codes being used (either 2008 or 2020). See: https://www.abs.gov.au/statistics/classifications/"),
  ALTER COLUMN code SET OPTIONS (description="Field of Research (FoR) subject short-code. Either a zero-padded 2,4 or 6 digit number, or 'MD' for multidisciplinary"),
  ALTER COLUMN name SET OPTIONS (description="Field of Research (FoR) subject title");

  -- tests
  SELECT 
    'there should be no intersection between the code sets' AS description,
    IF(COUNTIF(c != 1) = 0, 'pass', 'fail') AS test 
  FROM (SELECT COUNT(1) AS c FROM \`${project}.${dataset}.core_fors${version}\` GROUP BY code);
  SELECT
    'there should be no nulls or empty strings' AS description,
    IF(COUNT(1) = COUNTIF(vers='2008') + COUNTIF(vers='2020'), 'pass', 'fail') AS test1, 
    IF(COUNTIF(code IS NULL OR code = '') = 0                , 'pass', 'fail') AS test2,
    IF(COUNTIF(name IS NULL OR name = '') = 0                , 'pass', 'fail') AS test3,
    IF(COUNTIF(vers != '2008' AND vers != '2020') = 0        , 'pass', 'fail') AS test4
  FROM ${project}.${dataset}.core_fors${version};
END;
`;
const compile_all = (args = {}) => [compile(args)];
module.exports = { compile, compile_all };
if (require.main === module) require("app").cli_compile(compile_all);
