/*
## Summary
Creates a simplified table that can be used for RIES dashboards.

## Description
Download the data as a CSV to use with the dashboard. Some additional transformation is done 
within the RIES dashboard project.

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0

## Requires
table inst_summary_by_field_year
table inst_class_tallies_by_field_year

## Creates
table gui_table
*/
const compile = ({
  project = "",
  dataset = "",
  replace = false,
  start = 2011,
  finish = 2022,
  version = "",
}) => `
-- generated by: ${require("path").basename(__filename)}
BEGIN 

  -- generate 
  ${replace ? "CREATE OR REPLACE TABLE" : "CREATE TABLE IF NOT EXISTS"} \`${project}.${dataset}.heps_gui_table_2_${version}\` AS (
    SELECT 
      A.inst_code            AS idx_hep,
      A.field                AS idx_for,
      A.year                 AS idx_year,
      B.avg_rci_local        AS rci_local,
      B.avg_rci_world        AS rci_world,
      B.avg_rci_hpi          AS hpi_world,
      A.papers               AS sum_papers,
      A.citations            AS sum_citations,
      A.portions             AS sum_portions,
      A.papers_cent_world    AS cent_papers,
      A.citations_cent_world AS cent_citations,
      A.portions_cent_world  AS cent_portions,
      A.cpp_cent_world       AS cent_cpp,
    FROM      \`${project}.${dataset}.heps_summary_by_field_year_2_${version}\`       AS A
    LEFT JOIN \`${project}.${dataset}.heps_class_tallies_by_field_year_2_${version}\` AS B ON A.institution = B.institution AND A.field = B.field AND A.year = B.year
    WHERE A.year BETWEEN ${start} AND ${finish}
    ORDER BY idx_hep, idx_year, idx_for ASC
  );

  -- generate 
  ${replace ? "CREATE OR REPLACE TABLE" : "CREATE TABLE IF NOT EXISTS"} \`${project}.${dataset}.heps_gui_table_4_${version}\` AS (
    SELECT 
      A.inst_code            AS idx_hep,
      A.field                AS idx_for,
      A.year                 AS idx_year,
      B.avg_rci_local        AS rci_local,
      B.avg_rci_world        AS rci_world,
      B.avg_rci_hpi          AS hpi_world,
      A.papers               AS sum_papers,
      A.citations            AS sum_citations,
      A.portions             AS sum_portions,
      A.papers_cent_world    AS cent_papers,
      A.citations_cent_world AS cent_citations,
      A.portions_cent_world  AS cent_portions,
      A.cpp_cent_world       AS cent_cpp,
    FROM      \`${project}.${dataset}.heps_summary_by_field_year_4_${version}\`       AS A
    LEFT JOIN \`${project}.${dataset}.heps_class_tallies_by_field_year_4_${version}\` AS B ON A.institution = B.institution AND A.field = B.field AND A.year = B.year
    WHERE A.year BETWEEN ${start} AND ${finish}
    ORDER BY idx_hep, idx_year, idx_for ASC
  );  

  ${replace ? "CREATE OR REPLACE TABLE" : "CREATE TABLE IF NOT EXISTS"} \`${project}.${dataset}.heps_gui_table${version}\` AS (
    SELECT * FROM \`${project}.${dataset}.heps_gui_table_2_${version}\`
    UNION ALL
    SELECT * FROM \`${project}.${dataset}.heps_gui_table_4_${version}\`
    ORDER BY idx_hep, idx_year, idx_for
  );
END;
`;
const compile_all = (args = {}) => [compile(args)];
module.exports = { compile, compile_all };
if (require.main === module) require("app").cli_compile(compile_all);
