/*
## Summary
Exports datafiles for use with the RIES dashboard. One CSV for FoRs, another for FoEs. 

## License
Apache 2.0
*/

const { check_string } = require("../libraries/lib_checks");

const compile = ({
  project = "",
  dataset = "",
  filename = "",
  replace = false,
  version = "",
}) => {
  check_string(version);
  check_string(project);
  check_string(dataset);
  check_string(filename);
  return `
-- generated by: ${require("path").basename(__filename)}
BEGIN
  EXPORT DATA OPTIONS (
    uri         = 'gs://${project}-ries/tables/dashboard/${version}/${filename}_*.csv',
    format      = 'CSV',
    header      = true,
    overwrite   = ${replace}
  ) AS (
    SELECT 
      idx_hep       AS inst,
      IF(idx_for='MD','99',idx_for) AS conc,
      idx_year      AS year,
      rci_local     AS rciLocal,
      rci_world     AS rciGlobal,
      hpi_world     AS hpiGlobal,
      sum_papers    AS totalOutputs,
      sum_citations AS totalCitations
    FROM \`${project}.${dataset}.heps_gui_table${version}\`
  );

END;
`;
};
module.exports = compile;
