/*
## Summary
Imports raw data from GCS into the ISSNs table.

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0

## Requires
file coki.cloud

## Creates
table raw_issns
*/
const compile = ({ project = "", dataset = "", version = "" }) => `
-- generated by: ${require("path").basename(__filename)}
BEGIN
  LOAD DATA OVERWRITE \`${project}.${dataset}.raw_issns${version}\` (
    issn  STRING NOT NULL OPTIONS(description='ISSN'),
    issnl STRING NOT NULL OPTIONS(description='Linking ISSN'),
  )                       OPTIONS(description='Official ISSN -> ISSN-L mapping from https://www.issn.org/wp-content/uploads/2014/03/issnltables.zip')
  FROM FILES (
    format = 'JSON',
    uris = ['gs://${project}-ries/tables/raw_issns/data*.jsonl']
  );
END;
`;
const compile_all = (args = {}) => [compile(args)];
module.exports = { compile, compile_all };
if (require.main === module) require("app").cli_compile(compile_all);
