/*
## Summary
Imports raw data from GCS into the HEPs table.

## Contacts
julian.tonti-filippini@curtin.edu.au

## License
Apache 2.0

## Requires
file coki.cloud

## Creates
table raw_heps
*/
const compile = ({ project = "", dataset = "", version = "" }) => `
-- generated by: ${require("path").basename(__filename)}
BEGIN
  LOAD DATA OVERWRITE \`${project}.${dataset}.raw_heps${version}\` (
    ror  STRING OPTIONS(description='Research Organisation Registry unique identifier'),
    name STRING OPTIONS(description='Name of the research institution'),
  )             OPTIONS(description='List of Australian Higher Education Providers (HEPs) focused on by the ERA process')
  FROM FILES (
    format = 'JSON',
    uris = ['gs://${project}-ries/tables/raw_heps/data*.jsonl']
  );
END;`;
const compile_all = (args = {}) => [compile(args)];
module.exports = { compile, compile_all };
if (require.main === module) require("app").cli_compile(compile_all);
